//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class LoadWorldRequest : Message
    {
        public const string k_RosMessageName = "unity_msgs/LoadWorld";
        public override string RosMessageName => k_RosMessageName;

        public string world_name;
        public string world_path;
        public bool create_ground_plane;
        public Geometry.PoseMsg pose;
        public float width;
        public float height;
        public float[] origin;

        public LoadWorldRequest()
        {
            this.world_name = "";
            this.world_path = "";
            this.create_ground_plane = false;
            this.pose = new Geometry.PoseMsg();
            this.width = 0.0f;
            this.height = 0.0f;
            this.origin = new float[3];
        }

        public LoadWorldRequest(string world_name, string world_path, bool create_ground_plane, Geometry.PoseMsg pose, float width, float height, float[] origin)
        {
            this.world_name = world_name;
            this.world_path = world_path;
            this.create_ground_plane = create_ground_plane;
            this.pose = pose;
            this.width = width;
            this.height = height;
            this.origin = origin;
        }

        public static LoadWorldRequest Deserialize(MessageDeserializer deserializer) => new LoadWorldRequest(deserializer);

        private LoadWorldRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.world_name);
            deserializer.Read(out this.world_path);
            deserializer.Read(out this.create_ground_plane);
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
            deserializer.Read(out this.origin, sizeof(float), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.world_name);
            serializer.Write(this.world_path);
            serializer.Write(this.create_ground_plane);
            serializer.Write(this.pose);
            serializer.Write(this.width);
            serializer.Write(this.height);
            serializer.Write(this.origin);
        }

        public override string ToString()
        {
            return "LoadWorldRequest: " +
            "\nworld_name: " + world_name.ToString() +
            "\nworld_path: " + world_path.ToString() +
            "\ncreate_ground_plane: " + create_ground_plane.ToString() +
            "\npose: " + pose.ToString() +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString() +
            "\norigin: " + System.String.Join(", ", origin.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
