//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class MoveModelResponse : Message
    {
        public const string k_RosMessageName = "unity_msgs/MoveModel";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public string status_message;

        public MoveModelResponse()
        {
            this.success = false;
            this.status_message = "";
        }

        public MoveModelResponse(bool success, string status_message)
        {
            this.success = success;
            this.status_message = status_message;
        }

        public static MoveModelResponse Deserialize(MessageDeserializer deserializer) => new MoveModelResponse(deserializer);

        private MoveModelResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.status_message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.status_message);
        }

        public override string ToString()
        {
            return "MoveModelResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nstatus_message: " + status_message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
