//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Unity
{
    [Serializable]
    public class SpawnModelRequest : Message
    {
        public const string k_RosMessageName = "unity_msgs/SpawnModel";
        public override string RosMessageName => k_RosMessageName;

        public string model_name;
        public string model_namespace;
        public string reference_frame;
        public string model_urdf_path;
        public Geometry.PoseMsg initial_pose;
        public float[] additional_data;

        public SpawnModelRequest()
        {
            this.model_name = "";
            this.model_namespace = "";
            this.reference_frame = "";
            this.model_urdf_path = "";
            this.initial_pose = new Geometry.PoseMsg();
            this.additional_data = new float[10];
        }

        public SpawnModelRequest(string model_name, string model_namespace, string reference_frame, string model_urdf_path, Geometry.PoseMsg initial_pose, float[] additional_data)
        {
            this.model_name = model_name;
            this.model_namespace = model_namespace;
            this.reference_frame = reference_frame;
            this.model_urdf_path = model_urdf_path;
            this.initial_pose = initial_pose;
            this.additional_data = additional_data;
        }

        public static SpawnModelRequest Deserialize(MessageDeserializer deserializer) => new SpawnModelRequest(deserializer);

        private SpawnModelRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_name);
            deserializer.Read(out this.model_namespace);
            deserializer.Read(out this.reference_frame);
            deserializer.Read(out this.model_urdf_path);
            this.initial_pose = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.additional_data, sizeof(float), 10);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_name);
            serializer.Write(this.model_namespace);
            serializer.Write(this.reference_frame);
            serializer.Write(this.model_urdf_path);
            serializer.Write(this.initial_pose);
            serializer.Write(this.additional_data);
        }

        public override string ToString()
        {
            return "SpawnModelRequest: " +
            "\nmodel_name: " + model_name.ToString() +
            "\nmodel_namespace: " + model_namespace.ToString() +
            "\nreference_frame: " + reference_frame.ToString() +
            "\nmodel_urdf_path: " + model_urdf_path.ToString() +
            "\ninitial_pose: " + initial_pose.ToString() +
            "\nadditional_data: " + System.String.Join(", ", additional_data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
